apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: loan-app
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "YOUR_RDS_PASSWORD_HERE"
  IAM_DATABASE_URL: "postgres://postgres:YOUR_RDS_PASSWORD_HERE@YOUR_RDS_ENDPOINT:5432/iam_db?sslmode=require"
  LOAN_DATABASE_URL: "postgres://postgres:YOUR_RDS_PASSWORD_HERE@YOUR_RDS_ENDPOINT:5432/loan_db?sslmode=require"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.loan-app.svc.cluster.local:5672/"
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=placeholder;AccountKey=placeholder;EndpointSuffix=core.windows.net"
  AZURE_CONTAINER_NAME: "kyc-documents"
  DISCORD_WEBHOOK_URL: ""
