apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: loan-app
  labels:
    app: loan-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
      - name: loan-service
        image: aarghyan/loan-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: LOAN_DATABASE_URL
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_URL
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: AZURE_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AZURE_CONTAINER_NAME
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: jwt-keys-vol
          mountPath: /app/public.pem
          subPath: public.pem
          readOnly: true
      volumes:
      - name: jwt-keys-vol
        secret:
          secretName: jwt-keys
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: loan-app
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: loan-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loan-service-hpa
  namespace: loan-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loan-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
